# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_itc_user_interaction_percentage_scroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itc_user_interaction',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='itc_user_interaction',
            name='user_name',
        ),
    ]
