# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_heatmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itc_user_interaction',
            name='user_id',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='page_interaction',
            name='user_id',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
